version: '3.7'

services:
  rdf-differ-api:
    container_name: rdf-differ-api
    build:
      context: .
      dockerfile: compose/dev/api/Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - ${RDF_DIFFER_API_PORT}:${RDF_DIFFER_API_PORT}
    env_file: compose/dev/api/.dev

  rdf-differ-ui:
    container_name: rdf-differ-ui
    build:
      context: .
      dockerfile: compose/dev/ui/Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - ${UI_PORT}:${UI_PORT}
    env_file: compose/dev/ui/.dev

  fuseki:
    container_name: fuseki
    build: compose/production/fuseki
    volumes:
      - ${PWD}/${FUSEKI_DATA_FOLDER}/fuseki:/fuseki
    environment:
      - ADMIN_PASSWORD=admin
      - JVM_ARGS=-Xmx2g
    ports:
      - ${FUSEKI_PORT}:${FUSEKI_PORT}
