name: Docker build and push

on:
  release:
    types: [published]

jobs:
  main:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Define variables
        run: |
          # Hard coded variable
          echo "Dockerfile" > DOCKERFILE_NAME
          echo "meaningfy" > DOCKERHUB_USER
          echo "rdf-differ" > APP_NAME
          echo "$(cat DOCKERHUB_USER)/$(cat APP_NAME)" > DKR_HUB_URL
          #
          echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}
          date -d "-4 hours" "+%Y-%m-%d_%HH%Ms%S" > DATE_TIME
          # logically defined tags
          echo "$(cat DKR_HUB_URL):latest" > TAG_LATEST
          echo "$(cat DKR_HUB_URL):stable" > TAG_STABLE
          echo "$(cat DKR_HUB_URL):$(cat RELEASE_VERSION)" > TAG_VERSION
          echo "$(cat DKR_HUB_URL):$(cat RELEASE_VERSION)_$(cat DATE_TIME)" > TAG_BEST_PRACTICE
      - name: Show release version
        # now RELEASE_VERSION is an env variable
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          build-args: --env-file .env.prod
          push: true
          tags: |
            meaningfy/rdf-differ:latest
            meaningfy/rdf-differ:${{ env.RELEASE_VERSION }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
