version: '3'
services:
  fuseki:
    container_name: fuseki
    image: stain/jena-fuseki
    environment:
      - ADMIN_PASSWORD=admin
      - JVM_ARGS=-Xmx2g
    ports:
     - ${FUSEKI_PORT-3030}:3030
    volumes:
      - ${PWD}/${DATA_FOLDER}/fuseki:/fuseki