name: Docker build and push

on:
  release:
    types: [published]

jobs:
  main:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set env
        run: |
          echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}
      - name: Show release version
        # now RELEASE_VERSION is an env variable
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            meaningfy/rdf-differ:latest
            meaningfy/rdf-differ:${{ env.RELEASE_VERSION }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
